spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # eureka server에 등록되어있는 url을 가져오기 위한 속성값.
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000 # 1초동안 응답이 없으면 cirbreaker open 처리함
        response-timeout: 10s # 반응시간이 2초가 넘으면 에러처리
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true


info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"


logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 # 갯수만큼의 요청이 오면 서비스의 상태를 확인하는지.
      permittedNumberOfCallsInHalfOpenState: 2 # half open 상태를 처리할 때 설정한 요청의 갯수만큼이 올 떄 확안.
      failureRateThreshold: 50 # 숫자만큼 실패하면 open 상태로 바뀐다.
      waitDurationInOpenState: 10000 # 설정한 시간만큼 half open 상태로 둔다.

server:
  port: 8079