spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://192.168.219.106:8071/"  # 기본값
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:http://49.175.22.52:8071/"

---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: info
    org.springframework.web: info
    org.springframework.cloud.netflix: info

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000