server:
  port: 9000

spring:
  config:
    import: "optional:configserver:http://49.175.22.52:8071/"
  application:
    name: securityserver
  profiles:
    active: dev
  cloud:
    config:
      label: main

management:
  endpoints:
    shutdown:
      enabled: true

---
spring:
  config:
    import: "optional:configserver:http://49.175.22.52:8071/"
    activate:
      on-profile: dev


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://49.175.22.52:8070/eureka/

---
spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
    activate:
      on-profile: prod

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/