server:
  port: 1541

spring:
  application:
    name: "board"
  servlet:
    multipart:
      enabled: true
      max-request-size: 1MB
      max-file-size: 1MB
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: dev
logging:
  level:
    org.springframework: error
    com.backend: info
    root: warn
  pattern:
  endpoints:
    shutdown:
      enabled: true # 유레카의 서비스를 끌 수 있도록 하는 설정값.

com:
  backend:
    upload:
      path: /app/upload


